### ISSUE TITLE
Note is different in local language than in english (eng is updated)

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/CloudAppSecurityDocs.it-it#9]
Nota
Make sure that you choose apps that are supported by Conditional Access App Control. Conditional Access App Control supports apps that are configured with SAML single sign-on in Azure AD. For example, Office 365 applications are not configured with SAML so they are not currently supported.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6f895939-5862-2cfa-3c3d-0afdb95fbba4
* Version Independent ID: b44fdfcf-c0f7-e3f0-103f-2e4dd33a7c9d
* Content: [Distribuire il controllo delle app con l'accesso condizionale di Microsoft Cloud App Security per app di Azure AD](https://docs.microsoft.com/it-it/cloud-app-security/proxy-deployment-aad)
* Content Source: [CloudAppSecurityDocs/proxy-deployment-aad.md](https://github.com/MicrosoftDocs/CloudAppSecurityDocs.it-it/blob/live/CloudAppSecurityDocs/proxy-deployment-aad.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by CeciAc** [comment]
Hello, @grex86,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @grex86,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @grex86 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/cloud-app-security/proxy-deployment-aad. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
